### ISSUE TITLE
Broken bloopgun dependency in coursier install.

### ISSUE THREAD

**Issue by okennedy** [scalacenter/bloop#1682] opened 2022-02-17 16:10 UTC
The following issue comes up when installing bloop with coursier

```
https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
  100.0% [##########] 2.2 KiB (22.2 KiB / s)
https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.13/maven-metadata.xml
  No new update since 2022-02-16 13:29:29
Exception in thread "main" coursier.error.ResolutionError$CantDownloadModule: Error downloading ch.epfl.scala:bloopgun_2.13:latest.stable
  No latest stable version found in https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.13/maven-metadata.xml
	at coursier.Resolve$.$anonfun$validate$1(Resolve.scala:331)
        ...
```

It looks like there's no `latest.stable` record in the maven repository
```
$ curl https://repo1.maven.org/maven2/ch/epfl/scala/bloopgun_2.13/maven-metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>ch.epfl.scala</groupId>
  <artifactId>bloopgun_2.13</artifactId>
  <versioning>
    <latest>1.4.12-63-858a5944</latest>
    <release>1.4.12-63-858a5944</release>
    <versions>
      <version>1.4.12-46-0dc735af</version>
      <version>1.4.12-48-81973d63</version>
      <version>1.4.12-63-858a5944</version>
    </versions>
    <lastUpdated>20220216132928</lastUpdated>
  </versioning>
</metadata>
```

**Comment by tgodzik** [comment] 2022-02-17 16:13
Thanks for reporting! It's caused by https://github.com/coursier/coursier/issues/2369, once we release a new version this should go away

**Comment by tgodzik** [comment] 2022-02-18 11:41
This should now be fixed with the new release.

**Closed by tgodzik** 2022-02-18 11:41 UTC
