### ISSUE TITLE
Bloop does not seem to handle compiler crashes

### ISSUE THREAD

**Issue by propensive** [scalacenter/bloop#393] opened 2018-03-26 15:51 UTC
If you write some code which causes `scalac` to crash (i.e. print out a stack trace), the bloop front-end does not terminate. Instead it just hangs until you press Ctrl+C. This does not seem to have any lasting damage, though I would not be surprised if it tied up one hot-compiler thread permanently, until you restart the server.

**Comment by jvican** [comment] 2018-03-26 15:57
Can you elaborate on what's happening and provide a way to reproduce? I don't quite get what you mean by "Bloop frontend does not terminate". It would be good if you can try with one of the latest versions to check if you can reproduce `1.0.0-M7+34-92721ec4`.

**Comment by propensive** [comment] 2018-03-27 01:07
Sorry if it wasn't clear. As I understand it, the front-end process which launches the compilation pipes the output from `scalac` back to the user's terminal. Under normal circumstances, when `scalac` has finished compiling, the thing I'm calling the "frontend process" (i.e. the nailgun python script that communicates with the bloop server) receives some indication from `scalac` that it has finished (I'm guessing a stream gets closed), and it knows that it has nothing more to do, so it terminates itself.

In my scenario, when `scalac` crashes abnormally (and I don't have a particularly good way of reproducing this, as it requires a reasonably serious bug in the compiler), the nailgun script never realises that the stream has ended, and so it sits there, still running, listening to a stream which will never send any more data.

**Comment by jvican** [comment] 2018-03-27 06:30
Do you use file watching? (I assume not, but I need a confirmation) This seems weird, if there’s a compile error that throws an exception that is caught by our monix task engine. 

When you say “compiler bug”, do you mean that scalac throws an exception while compiling code or while initializing the compiler?

**Comment by propensive** [comment] 2018-03-27 18:16
I wasn't using file-watching (that still isn't working for me with M7). But I can now confirm that this doesn't always happen: I have encountered two compiler crashes, one "hung", and the other one exited normally.

When I say compiler crash, I mean a definite bug in the compiler, where it crashes when trying to compile code (in typer, in my case).

So this most recent time, it exited normally, but it also exited with a `0` exit status, when we can probably agree it should have bene a `1`. ;)

**Comment by jvican** [comment] 2018-03-28 10:20
> So this most recent time, it exited normally, but it also exited with a 0 exit status, when we can probably agree it should have bene a 1. ;)

Yup, at some point I'll need to get back to that and get accurate exit status codes. I'm leaving this open for now, and not labelling it as a bug, because it's not clear what this ticket is about. If someone gets to reproduce it again, I'll look more closely into it.

**Comment by propensive** [comment] 2018-03-29 15:23
Seems reasonable. These sorts of things are difficult to reproduce, but having a background awareness of this should provide context to someone the next time it happens.

**Comment by jvican** [comment] 2018-06-01 13:30
This has been sitting in the issue tracker for a long time and we don't have a reproduction for it. So i'm closing it! If someone gets to reproduce it and we can act on the ticket, ask for it to be reopened please! :smile:

**Closed by jvican** 2018-06-01 13:30 UTC
Labels: task / compile, under investigation
