### ISSUE TITLE
How do I pass arguments to scalatest main runner in v1.4.1

### ISSUE THREAD

**Issue by davidmlw** [scalacenter/bloop#1288] opened 2020-05-21 17:10 UTC
For some reason, I need run org.scalatest.tools.Runner from bloop run. In bloop 1.4.0-RC1, it is working:

`bloop run --projects MyProject --main org.scalatest.tools.Runner --args -oF --args -s --args MySpec --args -Dkey=value --args -Dkey2=value2`

But in bloop 1.4.1, the `--args -Dkey=value --args -Dkey2=value2` does not pass the key values to the runner. I tried this, not working:

`bloop run --projects MyProject --main org.scalatest.tools.Runner --args -oF --args -s --args MySpec -- -Dkey=value -Dkey2=value2`

So the question is how to pass arguments to a scala main and then pass to internal

**Comment by jvican** [comment] 2020-05-22 10:23
Thanks for reporting. This is addressed in the Getting Started guide, you need to add those arguments after `--`. Please see https://scalacenter.github.io/bloop/docs/cli/tutorial#pass-jvm-arguments-to-run and https://scalacenter.github.io/bloop/docs/cli/tutorial#pass-test-arguments-to-test

**Closed** 2020-05-22 10:24 UTC
Labels: docs, task / run, task / test

**Comment by davidmlw** [comment] 2020-05-22 13:42
I tried -- solution. I am pretty sure that 1.4.1 and 1.4.0-RC1 have different behavior. I also find that, I run 'bloop server' with 1.4.1, and run 'bloop run --projects MyProject --main org.scalatest.tools.Runner -- ......` with 1.4.1, not working, with 1.4.0-RC1, working.

The behavior is the "-Dkey=value" are not passed in, but others are right.

**Comment by kammoh** [comment] 2021-04-15 03:17
I also the see issue in bloop 1.4.8 and master.
I'm trying to pass config map to scalatest.
The same code works fine using `sbt`.
```
$ sbt "root/testOnly MySpec -- -Dasdf=123"
[info] compiling ...
MySpec:
configMap=Map(asdf -> 123)

$ bloop test root --only MySpec -- -Dasdf=123
MySpec:
configMap=Map()
```
I also tried the `--args` flag and different variations of quotations. None works. 
Tried bloop "1.4.8" and "v1.4.8-19-4d9f966b", also JDK 8 and 11.

```
$ bloop about
bloop v1.4.8-19-4d9f966b

Using Scala v2.12.8 and Zinc v1.3.0-M4+46-edbe573e
Running on Java JDK v11.0.10 (/usr/local/Cellar/openjdk@11/11.0.10/libexec/openjdk.jdk/Contents/Home)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center (Jorge Vicente Cantero, Martin Duhem)
```
Should I create a new issue or can this one be reopened?

**Comment by tgodzik** [comment] 2021-04-15 07:14
Hey @kammoh  thanks for letting us know. Would it work with `-J-Dasdf=123` ? Just guessing here, because I haven't dug match into the problem, we can open another issue if that doesn't help.

**Comment by kammoh** [comment] 2021-04-15 17:38
Thanks @tgodzik for the feedback. Unfortunately it did not work. I opened #1490.
I'm running on macOS and OpenJDK 11/8. Does it work on under other OSes and/or JVM versions?

**Comment by tgodzik** [comment] 2021-04-15 17:39
It should work there.

**Comment by kammoh** [comment] 2025-03-16 19:03
Almost 5 years later... the issue is _still_ **not** resolved!

**Comment by tgodzik** [comment] 2025-03-16 19:17
This is an open source project, where everyone can contribute and try to fix their issues if the maintainers are unable to do it or do it in a timely matter. Also, there is no time guarantees here as open source is **free** and not really a product that you pay for.

As a side note, writing `Almost 5 years later... the issue is still not resolved!` will not make anyone fix the issue faster and will most likely achieve an opposite result.
