### ISSUE TITLE
Bloop launcher stuck on Appveyor CI

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#790] opened 2019-01-12 11:52 UTC
To reproduce

I have an `appveyor.yml` like this in Metals.
```yml
build_script:
  - java -Djna.nosys=true -jar metals\src\main\resources\bloop-launch.jar --skip-bsp-connection 1.2.1
  - sbt publishLocal
```

It gets stuck at the following line https://ci.appveyor.com/project/scalameta/metals#L230
```
Sleeping for 400ms until we run `bloop about` to check server
```

PR: https://github.com/scalameta/metals/pull/462

**Comment by olafurpg** [comment] 2019-01-12 11:53
Without `-Djna.nosys=true`, I get the following error

```
ception in thread "main" java.lang.Error: 
There is an incompatible JNA native library installed on this system
Expected: 5.2.0
Found:    3.2.1
C:\Program Files\Java\jdk1.8.0\bin;C:\windows\Sun\Java\bin;C:\windows\system32;C:\windows;C:\sbt\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Perl\site\bin;C:\Perl\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\7-Zip;C:\Program Files\Microsoft\Web Platform Installer\;C:\Tools\GitVersion;C:\Tools\PsTools;C:\Program Files\Git LFS;C:\Program Files (x86)\Subversion\bin;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Tools\WebDriver;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.4\;C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin;C:\Ruby193\bin;C:\Tools\NUnit\bin;C:\Tools\xUnit;C:\Tools\MSpec;C:\Tools\Coverity\bin;C:\Program Files (x86)\CMake\bin;C:\go\bin;C:\Program Files\Java\jdk1.8.0\bin;C:\Python27;C:\Program Files\nodejs;C:\Program Files (x86)\iojs;C:\Program Files\iojs;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\MSBuild\14.0\Bin;C:\Tools\NuGet;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Apache\Maven\bin;C:\Python27\Scripts;C:\Tools\NUnit3;C:\Program Files\Mercurial\;C:\Program Files\dotnet\;C:\Tools\curl\bin;C:\Program Files\Amazon\AWSCLI\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140;C:\Tools\vcpkg;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\erl9.2\bin;C:\Program Files (x86)\NSIS;C:\Tools\Octopus;C:\Program Files\Git\cmd;C:\Program Files\Git\usr\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\LLVM\bin;C:\Program Files (x86)\Yarn\bin\;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\PowerShell\6\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\nodejs\;C:\Users\appveyor\.dotnet\tools;C:\Users\appveyor\AppData\Local\Yarn\bin;C:\Users\appveyor\AppData\Roaming\npm;C:\Program Files\AppVeyor\BuildAgent\;..
To resolve this issue you may do one of the following:
 - remove or uninstall the offending library
 - set the system property jna.nosys=true
 - set jna.boot.library.path to include the path to the version of the 
   jnidispatch library included with the JNA jar file you are using
	at com.sun.jna.Native.<clinit>(Native.java:199)
	at com.sun.jna.Pointer.<clinit>(Pointer.java:54)

```

It might be related but I'm not sure.

**Comment by jvican** [comment] 2019-01-13 00:32
I have:
  
* created my own bootstrapped launcher with coursier 1.1.0-M8
* run the launcher with `bloop-launcher --skip-bsp-connection 1.2.1`
  
However, I cannot reproduce on a Windows 10 machine with Java 8.
  
Important considerations:
  
1. I have not had any problem with jna (why is the jna issue happening to you?)
1. I run the launcher in an environment with no trace of bloop (just as appveyor)
1. The launcher installs bloop successfully
2. The script finishes after 6 "Sleeping for 400ms until we run `bloop about` to check server" logs
3. Script finishes with a 0 exit status code

**Comment by jvican** [comment] 2019-01-14 14:56
I'm closing since I couldn't reproduce. Let's open again when a reproduction is found and I can I investigate further

**Closed by jvican** 2019-01-14 14:56 UTC
Labels: launcher, under investigation
