### ISSUE TITLE
Find solution for too many "computing" spans

### ISSUE THREAD

**Issue by japgolly** [scalacenter/bloop#929] opened 2019-06-08 02:33 UTC
Looking at a trace, most level-2 spans seem to be either "compile <module>" or "computing <module>". Only really big projects (i.e. lots of modules) it becomes really, really hard to make sense of all the info holistically because there are so many tiny "computing" spans. Ideally I'd like to just see all the "compiling" spans so that 1) all spans fits on my screen :D and 2) I can get a quick understanding of module sizes and dependencies.

That's the problem, any solution would do, even a bloop flag :)

*(Ideally Jaeger or Zipkin would just have a filtering option but it is what it is I guess)*

**Comment by jvican** [comment] 2019-06-08 19:14
Thanks for your feedback @japgolly 😺 

> Ideally I'd like to just see all the "compiling" spans so that 1) all spans fits on my screen :D and 2) I can get a quick understanding of module sizes and dependencies.

I'm not sure I know exactly what the issue is, could you provide a screenshot?
  
> Only really big projects (i.e. lots of modules) it becomes really, really hard to make sense of all the info holistically because there are so many tiny "computing" spans
  
Have you realized Zipkin allows to collapse all traces so that you can be the one expanding them incrementally and making better sense of the output?

**Comment by japgolly** [comment] 2019-06-08 23:14
Hey @jvican, yes I'm aware you can collapse/expand spans, sorry I should've been clearer about that. I collapse everything (`]` in Jaeger) and then expand just the next level (`O` in Jaeger) which I was hoping would give me just the modules themselves but because my project is huge it looks like this:

![Screenshot_2019-06-09_09-07-12](https://user-images.githubusercontent.com/202935/59153164-8f92c980-8a96-11e9-9243-27e4513b40e5.png)

You can see there are lots of computing and compiling spans, and notice the scroll bar hahaha.

**Comment by jvican** [comment] 2019-06-13 15:33
Aha, I understand now better! I understand the motivation, however I think I won't be able to work any time soon on this and the feature is quite niche. I'd be happy to accept a contribution with this change but I'm closing the ticket for now :smile:

**Closed by jvican** 2019-06-13 15:33 UTC
Labels: enhancement, tracing

**Comment by japgolly** [comment] 2019-06-14 23:30
Ok no worries & thanks!
