### ISSUE TITLE
Stale zipkin threads increase CPU time

### ISSUE THREAD

**Issue by tgodzik** [scalacenter/bloop#1362] opened 2020-08-28 17:33 UTC
It seems to happen to quite few people that at some point Bloop start using all available processor power and the only solution is to kill it.

Took a stack trace:

[jstack.txt](https://github.com/scalacenter/bloop/files/5143391/jstack.txt)

what struck me the most is that it looks like there are 932 zipkin threads and I am not doing anything with zipkin at all. Shouldn't it be disabled normally?

Any ideas what is happening?

**Comment by tgodzik** [comment] 2020-08-28 17:50
It also seems to happen more if I compile Scala 3, although in this case I was working on Metals itself.

**Comment by jvican** [comment] 2020-09-16 08:09
Hey @tgodzik thanks for the report! I'll give this some priority and investigate what's going on. The zipkin thread detail is a good lead.

**Comment by ornicar** [comment] 2020-09-24 07:02
Hi and thank you so much for bloop.

I'm using it to develop lichess.org ([source code](https://github.com/ornicar/lila)) and running into this issue all the time. After using bloop for a few minutes, it will start hogging a CPU at 100%.
Killing the bloop process then running `bloop compile lila` immediately gets a CPU indefinitely back to 100%.

Removing all bloop files from the project will get rid of the problem for a few minutes.

Here's what it looks like in the CPU sampler of visualVM:
![](https://i.imgur.com/yaIjXuh.png)

```
java -version
java version "11.0.8.0.2" 2020-07-09 LTS
Java(TM) SE Runtime Environment GraalVM EE 20.2.0 (build 11.0.8.0.2+1-LTS-jvmci-20.2-b03)
Java HotSpot(TM) 64-Bit Server VM GraalVM EE 20.2.0 (build 11.0.8.0.2+1-LTS-jvmci-20.2-b03, mixed mode, sharing)
```
scala: 2.13.3
OS: Linux 5.8.10-arch1-1

If there is anything I could do to help figuring this out, please let me know.

**Comment by jvican** [comment] 2020-09-24 10:09
Hi @ornicar, thanks for the detailed comment! We've used lichess in our community build to test for compilation correctness and speed in the past, it's great you're using bloop.
  
I'm going to investigate what's going on by first trying to reproduce the issue in my macOS machine. Will get back to you to let you know if I've succeeded. If you could share a yourkit cpu profile with the methods that hog the CPU that will simplify this investigation much further.

**Comment by jvican** [comment] 2020-09-24 10:33
I can't reproduce. I've exported the project manually with `sbt bloopInstall`, compiled the whole project several times, made some changes in code, recompiled, and after the compilations the bloop server gets back to idle CPU consumption (or almost insignificant, e.g. 1-3%).

**Comment by ornicar** [comment] 2020-09-24 10:38
Hmm. Could it have to do with me not only compiling but also running lila? I use

`bloop run lila -m play.core.server.ProdServerStart -c /home/thib/lila/.bloop`

I could also try to produce a zip of the entire project when it fails, so you could try to reproduce with that?

In case you want to discuss this in near real-time, you could join our discord server dev channel: https://discord.gg/VkbG3P

**Comment by tgodzik** [comment] 2020-09-24 10:44
> I can't reproduce. I've exported the project manually with `sbt bloopInstall`, compiled the whole project several times, made some changes in code, recompiled, and after the compilations the bloop server gets back to idle CPU consumption (or almost insignificant, e.g. 1-3%).

For me it happens very rarely with normal usage - happened realy only once. More often on Dotty projects, but usually after doing a lot of recompilations in a larger codebase.

I will try out lila too to see if maybe I can reproduce it.

One thing I confirmed is that it seems new zipkin thread is created on each compile request.

**Comment by tgodzik** [comment] 2020-09-24 11:13
Cannot seems to reproduce the issue with compiling lila on linux either :/

**Comment by ornicar** [comment] 2020-09-25 09:16
I'm uploading a tgz of the entire project in the current broken state, will update the issue when ready.

Notes:
`bloop compile user` always fine
`bloop compile team` first run always fine. Second run always breaks (i.e. creates the 100% CPU thread)
`bloop compile api` always breaks
`bloop compile app` always breaks

**Comment by ornicar** [comment] 2020-09-27 11:51
The TGZ has been moved to there: http://khiaw.lichess.ovh/public/lila.tgz

**Comment by Duhemm** [comment] 2020-10-21 15:12
Fixed in #1386

**Closed by Duhemm** 2020-10-21 15:12 UTC
Labels: bug, task / compile, tracing

**Comment by ornicar** [comment] 2020-10-21 21:58
Amazing. That makes me very happy. Congrats and thank you so much!

**Comment by ornicar** [comment] 2020-10-29 08:09
Any ETA for a release with that fix? I tried building bloop for myself but that didn't work. Also there's no artifacts in the github actions because the builds failed: https://github.com/scalacenter/bloop/actions

I would really love to use bloop again <3

**Comment by tgodzik** [comment] 2020-10-29 10:11
The recent SNAPSHOT builds have failed, I will try to take a look into it today.
