### ISSUE TITLE
Unexpected error during installation on Mac OS

### ISSUE THREAD

**Issue by aywengo** [scalacenter/bloop#1275] opened 2020-05-11 11:10 UTC
`brew install scalacenter/bloop/bloop` is failing on Mac OS Catalina  with 

> curl: (22) The requested URL returned error: 404 Not Found
> Error: An exception occurred within a child process:
>   DownloadError: Failed to download resource "bloop"
> Download failed: https://github.com/scalacenter/bloop/releases/download/v1.4.0-RC3/bloop-coursier.json.json

Full output:
```
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

Error: No available formula with the name "bloop"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
romeo@MacBook-Pro-Roman pragmatic-play-casino % brew install scalacenter/bloop/bloop
==> Tapping scalacenter/bloop
Cloning into '/usr/local/Homebrew/Library/Taps/scalacenter/homebrew-bloop'...
remote: Enumerating objects: 20, done.
remote: Counting objects: 100% (20/20), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 230 (delta 8), reused 12 (delta 0), pack-reused 210
Receiving objects: 100% (230/230), 42.60 KiB | 484.00 KiB/s, done.
Resolving deltas: 100% (127/127), done.
Tapped 1 formula (28 files, 80.4KB).
==> Installing bloop from scalacenter/bloop
==> Tapping coursier/formulas
Cloning into '/usr/local/Homebrew/Library/Taps/coursier/homebrew-formulas'...
remote: Enumerating objects: 75, done.
remote: Counting objects: 100% (75/75), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 178 (delta 24), reused 74 (delta 24), pack-reused 103
Receiving objects: 100% (178/178), 23.72 KiB | 693.00 KiB/s, done.
Resolving deltas: 100% (55/55), done.
Tapped 1 formula (27 files, 55.4KB).
==> Installing dependencies for scalacenter/bloop/bloop: bash-completion and coursier/formulas/coursier
==> Installing scalacenter/bloop/bloop dependency: bash-completion
==> Downloading https://homebrew.bintray.com/bottles/bash-completion-1.3_3.catal
######################################################################## 100.0%
==> Pouring bash-completion-1.3_3.catalina.bottle.tar.gz
==> Caveats
Add the following line to your ~/.bash_profile:
  [[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/bash-completion/1.3_3: 189 files, 607.9KB
==> Installing scalacenter/bloop/bloop dependency: coursier/formulas/coursi
==> Downloading https://github.com/coursier/coursier/releases/download/v2.0.0-RC6-15/cs-x86_64-apple-darw
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/37548601/8c87cb00-90
######################################################################## 100.0%
==> Downloading https://github.com/coursier/coursier/releases/download/v2.0.0-RC6-15/coursier
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/37548601/e89d2000-90
######################################################################## 100.0%
🍺  /usr/local/Cellar/coursier/2.0.0-RC6-15: 4 files, 50.3MB, built in 18 seconds
==> Installing scalacenter/bloop/bloop
==> Downloading https://github.com/scalacenter/bloop/releases/download/v1.4.0-RC3/bloop-coursier.json.jso
#=#=#
curl: (22) The requested URL returned error: 404 Not Found
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "bloop"
Download failed: https://github.com/scalacenter/bloop/releases/download/v1.4.0-RC3/bloop-coursier.json.json
```

**Comment by jvican** [comment] 2020-05-11 11:22
This is caused by some changes I'm doing to the installer. I'm working on this, you should be able to install bloop in 30 minutes.

**Comment by jvican** [comment] 2020-05-11 12:57
This is fixed now @aywengo :+1:

**Closed by jvican** 2020-05-11 12:57 UTC
Labels: bug, install

**Comment by aywengo** [comment] 2020-05-11 13:11
Thank you very much @jvican !
