### ISSUE TITLE
Cryptic 'Symbol is missing from the classpath' error

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#387] opened 2018-03-23 09:40 UTC
After running `bloop test testsJVM` in the scalameta repo several times to fix compilation errors I hit on the following cryptic error
```
[E] [E-1] Symbol 'type scala.meta.contrib.implicits.TreeExtensions' is missing from the classpath.
[E]       This symbol is required by 'trait scala.meta.contrib.implicits.implicits'.
[E]       Make sure that type TreeExtensions is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[E]       A full rebuild may help if 'implicits.class' was compiled against an incompatible version of scala.meta.contrib.implicits.
[E] [E-1] Symbol 'type scala.meta.contrib.implicits.Equality' is missing from the classpath.
[E]       This symbol is required by 'trait scala.meta.contrib.implicits.implicits'.
[E]       Make sure that type Equality is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[E]       A full rebuild may help if 'implicits.class' was compiled against an incompatible version of scala.meta.contrib.implicits.
Done compiling.
[E] 'contribJVM' failed to compile.
```

Workaround: `rm -rf .bloop-config/contribJVM` fixed the problem.

It's difficult to give a minimal repro since this happened after several invocations.

**Comment by olafurpg** [comment] 2018-03-23 12:15
No file watching at any point (which is unusual for me actually)

**Comment by jvican** [comment] 2018-03-25 11:41
It seems that this was reproduced in sbt too, which signals that it's a misbehaviour caused by Zinc (maybe because of the lacking incremental support). The fact that removing the target directory in `contribJVM` fixes the issue also tells us that there's something going on with the class files generated by `contribJVM`s compilation. I'm closing this since there's no way to reproduce and fix. If there's a reproduction, I suggest it's reported upstream in sbt/zinc.

**Closed by jvican** 2018-03-25 11:41 UTC
