### ISSUE TITLE
Don't test [DOCS] commits

### ISSUE THREAD

**Issue by Duhemm** [scalacenter/bloop#355] opened 2018-03-14 20:16 UTC
We used to skip the building and testing for commits that have `[DOCS]` in their body to save some time when modifying the docs, but unfortunately we started having some problems with Drone that would skip randomly the build.

This logic has been removed in #352, it would be nice to bring it back sometime.

**Comment by jvican** [comment] 2018-03-14 20:23
I think this is caused by `DRONE_COMMIT_MESSAGE` not being correctly populated by Drone. What I don't know is what triggered this error, since this worked correctly first.
  
I'd love if we have this feature back so that testing changes to the docs is way easier than it currently is.

**Comment by jvican** [comment] 2018-05-06 20:59
I'm closing this ticket. The changes in docs are usually correlated with changes in code, so I don't see much value in investing manpower to fix this.

**Closed by jvican** 2018-05-06 20:59 UTC
Labels: docs, enhancement, good first issue, help wanted
