### ISSUE TITLE
CLI command hangs forever because of a `SocketError`

### ISSUE THREAD

**Issue by isomarcte** [scalacenter/bloop#974] opened 2019-07-20 18:45 UTC
I'm getting a `SocketError` in my daemon logs after bloop has been running for only a few minutes. Initial commands, such as `bloop compile root` work fine, then after a bit all commands hang.

## System Logs ##

```
Jul 20 12:42:12 smaug bloop[607]: Client in /home/dstrawn/git/dreamwork/documents-genesys/.bloop disconnected with a 'SocketError' event. Cancelling tasks...
```

### OS ###

* Linux (Arch linux)

```shell
[SSH] [smaug]~ λ > cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

```shell
[SSH] [smaug]~ λ > uname -a
Linux smaug 5.2.1-arch1-1-ARCH #1 SMP PREEMPT Sun Jul 14 14:52:52 UTC 2019 x86_64 GNU/Linux
```

### Java Information ###

```shell
[SSH] [smaug]~ λ > archlinux-java get
java-8-openjdk
```

### Bloop Information ###

```shell
[SSH] [smaug]~ λ > pacman -Qi bloop
Name            : bloop
Version         : 1.3.2-1
Description     : Bloop gives you fast edit/compile/test workflows for Scala.
Architecture    : any
URL             : https://scalacenter.github.io/bloop/
Licenses        : Apache
Groups          : None
Provides        : None
Depends On      : scala  python
Optional Deps   : None
Required By     : None
Optional For    : metals
Conflicts With  : None
Replaces        : None
Installed Size  : 115.00 KiB
Packager        : Unknown Packager
Build Date      : Mon 10 Jun 2019 10:04:56 AM MDT
Install Date    : Mon 10 Jun 2019 10:05:06 AM MDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : None
```

**Comment by jvican** [comment] 2019-07-23 08:08
Thanks for reporting @isomarcte! This one looks interesting. Could you run all CLI commands with `--verbose` and analyze the output? It's weird that whenever a socket error is thrown and logged by the server, the client doesn't exit and hangs. And it's even weirder you can reproduce it consistently.

**Comment by isomarcte** [comment] 2019-07-23 15:06
@jvican will do.

**Comment by jvican** [comment] 2019-07-29 22:09
I'm planning to make some changes in this area soon, @isomarcte if you look into this let me know and I'll try to dig deeper into what might be causing this :smile:

**Comment by isomarcte** [comment] 2019-08-12 16:17
@jvican Sorry, I've been out of town (and away from my computer) for the past bit. I'll try to take a look at it today.

**Comment by jvican** [comment] 2019-08-31 18:50
@isomarcte In the next release I'm removing the python CLI, I hope this error will no longer exist. I think this error is caused by the Python script so I'm fairly confident this will not happen with our native GraalVM binary generated from our Scala implementation of nailgun.

**Comment by kurnevsky** [comment] 2019-09-16 18:40
It seems I faced the same issue. Running bloop compile with verbose writes only `[D] Computing sources and classpath hashes for engine` and then hangs.

**Comment by jvican** [comment] 2019-09-16 18:43
Can you drop by our Gitter channel and we try to find what the issue here is?

**Comment by jvican** [comment] 2019-10-05 22:58
So I'm closing this ticket because it's not actionable in its current form.
  
I believe the `SocketError` mentioned in the logs is not problematic, it's intead expected -- a mere side-effect of how the nailgun server works. I don't know if @kurnevsky's comment is related to the original bug reported in this ticket, but that one is fixed in the latest master.
  
If this issue can be reproduced after the upcoming release, then I'll have a closer look. I'm quite confident that using a native bloopgun-based CLI (instead of the python CLI that it's currently available to all of our users) will also help remove any problem that may occur while communicating with the server.

**Closed by jvican** 2019-10-05 22:58 UTC
Labels: build server, cli, nailgun, under investigation

**Comment by kurnevsky** [comment] 2019-10-08 12:29
It works for me now, thanks.
