### ISSUE TITLE
compile fails after sbt clean using sbt-buildinfo plugin

### ISSUE THREAD

**Issue by 123avi** [scalacenter/bloop#853] opened 2019-04-17 14:01 UTC
we are using the sbt-buildinfo plugin to create BuildInfo object.
when using `bloop compile foo` (after sbt clean command) it fails ` not found: object buildInfo`

**Comment by olafurpg** [comment] 2019-04-17 14:42
Thanks for reporting! I believe this is working as expected, you can run run `sbt compile` to re-generate the `BuildInfo.scala` file.

**Comment by 123avi** [comment] 2019-04-17 14:53
Thanks @olafurpg , you are correct of course, it seems more like a workaround than "working as expected" isn't it?  this is kind of missing the point of compiling using bloop

**Comment by jvican** [comment] 2019-04-18 08:27
@123avi Check the discussion I had with @cquiroz in Gitter for an explanation of what it happens and how it can be mitigated.
  
This is not a bug on our side, but rather a fallout from using sbt-buildinfo and the way it's set up, so I'm closing.

**Closed by jvican** 2019-04-18 08:27 UTC

**Comment by edrevo** [comment] 2019-07-30 10:32
Is there a link to the conversation on why this is by design? It is because BuildInfo is generated by an SBT plugin? I'm trying to make bloop work with a Play Framework project, but I'm getting a similar error with the Routes class (my guess is this is due to it also being a generated source file).

**Comment by jvican** [comment] 2019-07-30 16:31
It is this way by design because sbt exports projects to bloop that use its resources and when sbt `cleans` it removes those resources, therefore making them unavailable to bloop.
