### ISSUE TITLE
Compilation error caused by missing log4j class

### ISSUE THREAD

**Issue by pkolaczk** [scalacenter/bloop#957] opened 2019-07-10 18:12 UTC
```
[E] Unexpected error when compiling my-project: 'Lorg/apache/log4j/Level;'
java.lang.NoClassDefFoundError: Lorg/apache/log4j/Level;
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
        at java.lang.Class.privateGetPublicFields(Class.java:2614)
        at java.lang.Class.privateGetPublicFields(Class.java:2629)
        at java.lang.Class.getFields(Class.java:1557)
        at sbt.internal.inc.ClassToAPI$.structure(ClassToAPI.scala:180)
        at sbt.internal.inc.ClassToAPI$.x$2$lzycompute$1(ClassToAPI.scala:130)
        at sbt.internal.inc.ClassToAPI$.x$2$1(ClassToAPI.scala:130)
        at sbt.internal.inc.ClassToAPI$.instance$lzycompute$1(ClassToAPI.scala:130)
        at sbt.internal.inc.ClassToAPI$.instance$1(ClassToAPI.scala:130)
        at sbt.internal.inc.ClassToAPI$.$anonfun$toDefinitions0$1(ClassToAPI.scala:137)
        at xsbti.api.SafeLazyProxy$$anon$1.get(SafeLazyProxy.scala:30)
        at xsbti.api.SafeLazy$Impl.get(SafeLazy.java:62)
        at sbt.internal.inc.ClassToAPI$.$anonfun$process$2(ClassToAPI.scala:32)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:38)
        at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:38)
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:47)
        at sbt.internal.inc.ClassToAPI$.process(ClassToAPI.scala:32)
        at sbt.internal.inc.javac.AnalyzingJavaCompiler.readAPI$1(AnalyzingJavaCompiler.scala:169)
        at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$20(AnalyzingJavaCompiler.scala:190)
        at sbt.internal.inc.classfile.Analyze$.readInheritanceDependencies$1(Analyze.scala:179)
        at sbt.internal.inc.classfile.Analyze$.$anonfun$apply$15(Analyze.scala:185)
        at sbt.internal.inc.classfile.Analyze$.$anonfun$apply$15$adapted(Analyze.scala:99)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:792)
        at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
        at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
        at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:791)
        at sbt.internal.inc.classfile.Analyze$.apply(Analyze.scala:99)
        at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$19(AnalyzingJavaCompiler.scala:190)
        at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$19$adapted(AnalyzingJavaCompiler.scala:188)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:792)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:791)
        at sbt.internal.inc.javac.AnalyzingJavaCompiler.$anonfun$compile$17(AnalyzingJavaCompiler.scala:188)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.internal.inc.javac.AnalyzingJavaCompiler.timed(AnalyzingJavaCompiler.scala:234)
        at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:188)
        at sbt.internal.inc.javac.AnalyzingJavaCompiler.compile(AnalyzingJavaCompiler.scala:73)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$9(BloopHighLevelCompiler.scala:159)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$1(BloopHighLevelCompiler.scala:70)
        at bloop.tracing.BraveTracer.trace(BraveTracer.scala:31)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.timed$1(BloopHighLevelCompiler.scala:69)
        at sbt.internal.inc.bloop.internal.BloopHighLevelCompiler.$anonfun$compile$8(BloopHighLevelCompiler.scala:152)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
        at monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
        at monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Level
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 57 more

```

**Comment by tkroman** [comment] 2019-07-10 18:48
Do you have a repro? I have a project with log4j under bloop, works fine for me. Maybe some specific dependency setting?

**Comment by pkolaczk** [comment] 2019-07-11 06:37
This project doesn't have log4j in its dependencies. Why should it have? If looks like the exception is coming from bloop, so if bloop uses log4j it should put it on the classpath.

**Comment by pkolaczk** [comment] 2019-07-11 07:21
Adding log4j to the dependencies of the project helped. 

However I don't want to do that, because the project compiles fine in gradle without it.
`gradlew dependencies` on that project doesn't show log4j anywhere. There are slf4j dependencies only.

**Comment by pkolaczk** [comment] 2019-07-11 07:24
Here is the list of dependencies of that project:
```
"/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-client/2.7.1.4/79c17e9fab07be811aa43e52d51f6abbcb184fac/hadoop-client-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-aws/2.7.1.4/2513cf0b6dbedc550f3003647836f3d8441a75e4/hadoop-aws-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-common/2.7.1.4/f13c000b27246188ff7e192732524c1c818b5d2d/hadoop-common-2.7.1.4.jar",
            "/home/pkolaczk/Projekty/DataStax/dse/.bloop/dse-commons/build/classes",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-auth/2.7.1.4/82729ccf939c6b847f30e6fa3b4765bfb669ca30/hadoop-auth-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.directory.server/apacheds-kerberos-codec/2.0.0-M24/9219f9bb1e779ba0f56b8060dce161dbf78d45e2/apacheds-kerberos-codec-2.0.0-M24.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.directory.api/api-ldap-model/1.0.0.2.dse/25635ad2eadb5fc5ef2ce86a13544309f69aa42b/api-ldap-model-1.0.0.2.dse.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.mina/mina-core/2.0.17/7e10ec974760436d931f3e58be507d1957bcc8db/mina-core-2.0.17.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-azure/2.7.1.4/4f9d03ac20e98f3a6d3f3698886f168d7f8fadef/hadoop-azure-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/net.java.dev.jets3t/jets3t/0.9.4/c8ee6f998238747fcd2c390a3c13f3c9e086e92e/jets3t-0.9.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.jamesmurty.utils/java-xmlbuilder/1.2/fef5136a82e7ca7305f95255f12cc8cc5036375d/java-xmlbuilder-1.2.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/cglib/cglib/3.2.9/a4b7af2ea0a5ecad2d283c2fff119009f0c60d20/cglib-3.2.9.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.xerial.snappy/snappy-java/1.1.7.2/307b286efd119ad2c6d4291128bf110bddc68088/snappy-java-1.1.7.2.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-annotations/2.7.1.4/60da6236b0a6045dfe55b656caf8b3599e441dfa/hadoop-annotations-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-hdfs/2.7.1.4/c813fd14350f050aca5c1725564e36994c546203/hadoop-hdfs-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-mapreduce-client-app/2.7.1.4/97e9334fc0cdf4a024c43776a4db663a2048e649/hadoop-mapreduce-client-app-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-mapreduce-client-jobclient/2.7.1.4/26c48de68d60e9b2afbb14bef8d01bf2cc4b2082/hadoop-mapreduce-client-jobclient-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-mapreduce-client-shuffle/2.7.1.4/f6c0096997441be83f97cc83c76ba0136fc46c1a/hadoop-mapreduce-client-shuffle-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-mapreduce-client-common/2.7.1.4/fe53093b893b9def8768599da272c2e935ba70b7/hadoop-mapreduce-client-common-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-yarn-client/2.7.1.4/aca48ae086447fc1d60ef69862fd83565526b27c/hadoop-yarn-client-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-mapreduce-client-core/2.7.1.4/ea4436bfd3ae3f98a02544430d4af81c603721ac/hadoop-mapreduce-client-core-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-yarn-server-nodemanager/2.7.1.4/9fc73e4cf72b16d7a2d8208e1085246298caa877/hadoop-yarn-server-nodemanager-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-yarn-server-common/2.7.1.4/6a7bbdd103dac4f87cfc80fefcb354b4d949cd85/hadoop-yarn-server-common-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-yarn-common/2.7.1.4/6455ddc33194e80f4680cb8445d7b80314d9af66/hadoop-yarn-common-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.hadoop/hadoop-yarn-api/2.7.1.4/9b5ead1ce007be523b0d0404fe187901464a29ee/hadoop-yarn-api-2.7.1.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/19.0/6ce200f6b23222af3d8abb6b6459e6c44f4bb0e9/guava-19.0.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-math3/3.4.1/3ac44a8664228384bc68437264cf7c4cf112f579/commons-math3-3.4.1.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/xmlenc/xmlenc/0.52/d82554efbe65906d83b3d97bd7509289e9db561a/xmlenc-0.52.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/commons-net/commons-net/3.1/2298164a7c2484406f2aa5ac85b205d39019896f/commons-net-3.1.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/commons-collections/commons-collections/3.2.2/8ad72fe39fa8c91eaaf12aadb21e0c3661fe26d5/commons-collections-3.2.2.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/commons-configuration/commons-configuration/1.10/2b36e4adfb66d966c5aef2d73deb6be716389dc9/commons-configuration-1.10.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/commons-lang/commons-lang/2.6/ce1edb914c94ebc388f086c6827e8bdeec71ac2/commons-lang-2.6.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.avro/avro/1.8.2/91e3146dfff4bd510181032c8276a3a0130c0697/avro-1.8.2.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.google.protobuf/protobuf-java/2.5.0/a10732c76bfacdbd633a7eb0f7968b1059a65dfa/protobuf-java-2.5.0.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.2.4/a60a5e993c98c864010053cb901b7eab25306568/gson-2.2.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.jcraft/jsch/0.1.42/a86104b0f2e0c0bab5b0df836065823a99b5e334/jsch-0.1.42.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/3.0.0/5871fb60dc68d67da54a663c3fd636a10a532948/jsr305-3.0.0.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.htrace/htrace-core/3.1.0-incubating/f73606e7c9ede5802335c290bf47490ad6d51df3/htrace-core-3.1.0-incubating.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.zookeeper/zookeeper/3.4.6/1b2502e29da1ebaade2357cd1de35a855fa3755/zookeeper-3.4.6.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-compress/1.18/1191f9f2bc0c47a8cce69193feb1ff0a8bcb37d5/commons-compress-1.18.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.microsoft.azure/azure-storage/2.0.0/b970c65a38da0569013e0c76de7c404f842496c2/azure-storage-2.0.0.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.amazonaws/aws-java-sdk/1.7.4/2c24ccb6f1ab845a7df971951d4b41c709a6517d/aws-java-sdk-1.7.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.5.8/c27c9d6f15435dc2b6947112027b418b0eef32b9/httpclient-4.5.8.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.slf4j/jcl-over-slf4j/1.7.25/f8c32b13ff142a513eeb5b6330b1588dcb2c0461/jcl-over-slf4j-1.7.25.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/net.sf.ehcache/ehcache/2.10.4/9022b1eedfafa11039597b1c1918c1abe414df93/ehcache-2.10.4.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.directory.api/api-asn1-ber/1.0.0.2.dse/73b0765a8d460b804bb111c146707337aeee8e27/api-asn1-ber-1.0.0.2.dse.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.directory.api/api-util/1.0.0.2.dse/d88d56ee736d88099dba7c8639864687219e6d99/api-util-1.0.0.2.dse.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.directory.server/apacheds-i18n/2.0.0-M24/d351eefa0e1a4dbc1f23bd513417888cc73dc9cc/apacheds-i18n-2.0.0-M24.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.25/da76ca59f6a57ee3102f8f9bd9cee742973efa8a/slf4j-api-1.7.25.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpcore/4.4.11/de748cf874e4e193b42eceea9fe5574fabb9d4df/httpcore-4.4.11.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/commons-codec/commons-codec/1.10/4b95f4897fa13f2cd904aee711aeafc0c5295cd8/commons-codec-1.10.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.codehaus.jackson/jackson-mapper-asl/1.9.13/1ee2f2bed0e5dd29d1cb155a166e6f8d50bbddb7/jackson-mapper-asl-1.9.13.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.codehaus.jackson/jackson-core-asl/1.9.13/3c304d70f42f832e0a86d45bd437f692129299a4/jackson-core-asl-1.9.13.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/javax.activation/activation/1.1.1/485de3a253e23f645037828c07f1d7f1af40763a/activation-1.1.1.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.bouncycastle/bcprov-jdk15on/1.58/2c9aa1c4e3372b447ba5daabade4adf2a2264b12/bcprov-jdk15on-1.58.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/net.iharder/base64/2.3.8/7d2e2cea90cc51169fd02a35888820ab07f6d02f/base64-2.3.8.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm/7.0/d74d4ba0dee443f68fb2dcb7fcdb945a2cd89912/asm-7.0.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.ant/ant/1.10.3/88becdeb77cdd2457757b7268e1a10666c03d382/ant-1.10.3.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.directory.api/api-asn1-api/1.0.0.2.dse/b59143a4207b4a1d075d67c7e5caeafd302277aa/api-asn1-api-1.0.0.2.dse.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.directory.api/api-i18n/1.0.0.2.dse/c8fcb932cd454c2a07170a0af6cb38df4d731f6a/api-i18n-1.0.0.2.dse.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.tukaani/xz/1.6/5b6f921f1810bdf90e25471968f741f87168b64/xz-1.6.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/xerces/xercesImpl/2.9.1/7bc7e49ddfe4fb5f193ed37ecc96c12292c8ceb6/xercesImpl-2.9.1.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.fusesource.leveldbjni/leveldbjni-all/1.8/707350a2eeb1fa2ed77a32ddb3893ed308e941db/leveldbjni-all-1.8.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-lang3/3.5/6c6c702c89bfff3cd9e80b04d668c5e190d588c6/commons-lang3-3.5.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.ant/ant-launcher/1.10.3/9dd5189e7f561ca19833b4e3672720b9bc5cb2fe/ant-launcher-1.10.3.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.apache.servicemix.bundles/org.apache.servicemix.bundles.antlr/2.7.7_5/98912946d4e6746792c631d31a742f7d4d9c75a3/org.apache.servicemix.bundles.antlr-2.7.7_5.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/javax.xml.bind/jaxb-api/2.3.0/99f802e0cb3e953ba3d6e698795c4aeb98d37c48/jaxb-api-2.3.0.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.sun.jersey.contribs/jersey-guice/1.9/5963c28c47df7e5d6ad34cec80c071c368777f7b/jersey-guice-1.9.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.codehaus.jettison/jettison/1.1/1a01a2a1218fcf9faa2cc2a6ced025bdea687262/jettison-1.1.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/javax.inject/javax.inject/1/6975da39a7040257bd51d21a231b76c915872d38/javax.inject-1.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.datastax.dse/dse-java-driver-core/1.8.2-17eaece73-graph/be94bc115704138aa98fa1ecfa7d92b2d90a6d24/dse-java-driver-core-1.8.2-17eaece73-graph.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/commons-beanutils/commons-beanutils/1.9.3/c845703de334ddc6b4b3cd26835458cb1cba1f3d/commons-beanutils-1.9.3.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/javax.servlet.jsp/jsp-api/2.1/63f943103f250ef1f3a4d5e94d145a0f961f5316/jsp-api-2.1.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/javax.validation/validation-api/1.1.0.Final/8613ae82954779d518631e05daa73a6a954817d5/validation-api-1.1.0.Final.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/io.dropwizard.metrics/metrics-core/3.2.6/62fe170cffeded1cef60e9e3402a93b45ce14327/metrics-core-3.2.6.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.5/2852e6e05fbb95076fc091f6d1780f1f8fe35e0f/commons-io-2.5.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.diffplug.durian/durian/3.4.0/242ffce2fdf61e17ea8b6cd4487cae3e4f18eac7/durian-3.4.0.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/io.netty/netty-all/4.1.25.5.dse/c7a85ed263c77a044f19e0f1f763d2f0be3acdb2/netty-all-4.1.25.5.dse.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-posix/3.0.44/1f8e4551454e613c04f6d4045ed9d5b98e21980f/jnr-posix-3.0.44.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-ffi/2.1.7/31a7391a212069303935a1df29566b7372d3ef9f/jnr-ffi-2.1.7.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/7.0/478006d07b7c561ae3a92ddc1829bca81ae0cdd1/asm-commons-7.0.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-util/7.0/18d4d07010c24405129a6dbb0e92057f8779fb9d/asm-util-7.0.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-analysis/7.0/4b310d20d6f1c6b7197a75f1b5d69f169bc8ac1f/asm-analysis-7.0.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-tree/7.0/29bc62dcb85573af6e62e5b2d735ef65966c4180/asm-tree-7.0.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.github.jnr/jffi/1.2.16/5c1149dfcc9a16f85c8d9b8797f03806667cb9f1/jffi-1.2.16.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.github.jnr/jffi/1.2.16/3c1f0edf2df2c6e0419d60d0baa59659211624cb/jffi-1.2.16-native.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-x86asm/1.0.2/6936bbd6c5b235665d87bd450f5e13b52d4b48/jnr-x86asm-1.0.2.jar",
            "/home/pkolaczk/.gradle/caches/modules-2/files-2.1/com.github.jnr/jnr-constants/0.9.9/33f23994e09aeb49880aa01e12e8e9eff058c14c/jnr-constants-0.9.9.jar"
        ],
```

**Comment by jvican** [comment] 2019-07-15 07:45
@pkolaczk What do you have in the scala jars configuration field?
  
You should only have the jars of the scala artifacts (library, reflect, compiler) + jline. If that's fine, then I guess there's nothing we can do here until we have a small reproduction. I don't understand why this is happening, the error comes indeed from bloop, as if some dependency in your project was being picked over a dependency in bloop. The only case I can think of where this could happen is if there  were some unexpected dependencies in the `scala.jars` field of your JSON file.

**Comment by pkolaczk** [comment] 2019-07-15 08:48
There is no scala section at all, only java section:

```    
        "out" : "/home/pkolaczk/Projekty/xxxxxxxxxxxxxxxxx/build",
        "classesDir" : "/home/pkolaczk/Projekty/xxxxxxxxxxxxxxxxxxx/build/classes",
        "resources" : [
            "/home/pkolaczk/Projekty/xxxxxxxxxxxxxxxxxxxxxxxxxx/src/main/resources"
        ],   
        "java" : {
            "options" : [
                "-target",
                "1.8",
                "-source",
                "1.8",
                "-encoding",
                "UTF-8",
                "-g",
                "-sourcepath",
                "-proc:none",
                "-XDuseUnsharedTable=true"
            ]
        },
        "platform" : {
            "name" : "jvm",
            "config" : {
                "home" : "/opt/jdk1.8.0_201",
                "options" : [
                ]
            },
            "mainClass" : [
            ]
        },
        "resolution" : {
```

**Comment by jvican** [comment] 2019-07-15 08:59
It's likely the issue here is the resources. I guess you have a resource file configuring slf4j to use log4j, right? We add the resources to the compile classpath so that might be the reason why this is failing.

**Comment by pkolaczk** [comment] 2019-07-17 16:45
There are no resources in this project.
But maybe there are resources in some of the dependency jars?

**Comment by jvican** [comment] 2019-07-17 17:17
Yes, that's the most likely. A reproduction here would be useful. If we confirm this is the case, the fix would probably be to whitelist the access to log-related resources (log4j, jul) from the compiler classloader owned by Zinc. But it's weird that this is not happening in Gradle itself, I wonder if I'm missing something or there's some special configuration of your project in the Gradle build.

**Comment by schleumer** [comment] 2019-07-29 15:20
I don't if related, but somehow i'm getting "Unexpected error when compiling", but mine is about `java.sql`:

```
Unexpected error when compiling projectName: 'java/sql/ResultSetMetaData' 
```

I can't create a repro now, but i can relate that i'm using Slick with PostgreSQL.

**Comment by jvican** [comment] 2019-08-08 07:22
@schleumer Interesting. Would be lovely if you can provide a repro and I can look into this, your error seems to suggests this issue isn't caused solely with resources! In the meanwhile I'm closing this ticket until we have something actionable.

**Comment by schleumer** [comment] 2019-08-09 16:30
Done that! https://github.com/schleumer/bloop-repro-957

**Comment by schleumer** [comment] 2019-08-09 16:56
Just for report, worked in:
✅ OpenJDK8
❌ OpenJDK10
❌ OpenJDK11
❌ OpenJDK12


Somehow worked on Oracle's JDK12 🤔

**Comment by nafg** [comment] 2019-08-20 06:36
I'm having the same error as @schleumer

**Comment by nafg** [comment] 2019-08-20 06:43
...and switching the bloop server from java 10 to 8 worked (via `sudo update-alternatives --config java`)! Thanks reporting that factor!

**Comment by rtar** [comment] 2019-09-23 14:06
I wonder if anyone found workaround for this as it is effectively blocking Slick development using Bloop on JDK11.

**Comment by jvican** [comment] 2019-09-24 17:22
I've done some progress understanding what's going on here, I think it's related to the fact that we don't use the same `bootclasspath` in JDK 8 than JDK 11.
  
Here's the `bootclasspath` in JDK 8:

```
	-bootclasspath
	/usr/lib/jvm/java-8-graal/jre/lib/resources.jar:/usr/lib/jvm/java-8-graal/jre/lib/rt.jar:/usr/lib/jvm/java-8-graal/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-graal/jre/lib/jsse.jar:/usr/lib/jvm/java-8-graal/jre/lib/jce.jar:/usr/lib/jvm/java-8-graal/jre/lib/charsets.jar:/usr/lib/jvm/java-8-graal/jre/lib/jfr.jar:/usr/lib/jvm/java-8-graal/jre/lib/jvmci-services.jar:/usr/lib/jvm/java-8-graal/jre/classes:/usr/lib/jvm/java-8-graal/jre/lib/boot/graaljs-scriptengine.jar:/usr/lib/jvm/java-8-graal/jre/lib/boot/graal-sdk.src.zip:/usr/lib/jvm/java-8-graal/jre/lib/boot/graal-sdk.jar:/home/jvican/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.8.jar

```

Here's in JDK 11:
```
	-bootclasspath
	/home/jvican/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.8.jar
```
  
I need to figure out why that's not the case. I'll keep you updated.

**Comment by jvican** [comment] 2019-09-24 17:39
Alright, I think I have a fix. If successful will open PR soon.

**Comment by jvican** [comment] 2019-09-24 21:52
Alright @schleumer your issue is now fixed, a fix will be soon available in master. The original issue you reported and the one @pkolaczk are fundamentally different, I think @pkolaczk's is related to the compilation engine while yours it's related to a patch we were missing to fully support Java platforms greater or equal than 9.
  
I'm nonetheless going to mark the fix for this issue as a fix for this ticket. I believe @pkolaczk's issue will be fixed in latest master given some unrelated changes I've done in the compilation engine. If that's not the case, then we can create a new ticket, find a way to repro the issue and find out what's missing.

**Closed** 2019-09-29 22:51 UTC
Labels: task / compile, under investigation
