### ISSUE TITLE
Can't use cats-tagless macros with bloop

### ISSUE THREAD

**Issue by ytaras** [scalacenter/bloop#820] opened 2019-02-19 08:03 UTC
cats-tagless project uses scalameta-paradise macros to generate some boilerplate code. Unfortunately, those don't work with bloop. Looks like that macro expansion doesn't get called at all, however I don't know a way of confirming that or getting more debug output. 

I've assembled a simple showcase - https://github.com/ytaras/tagless_failure_showcase

The same project compiles if I use pure sbt, but fails when I try to compile it with bloop

I've opened an [issue](https://github.com/typelevel/cats-tagless/issues/20) in cats-tagless tracker and team suggested that bloop doesn't support scalameta-paradise; but I haven't been able to find that in a bloop documentation

**Comment by jvican** [comment] 2019-02-19 08:23
Duplicate of https://github.com/scalacenter/bloop/issues/817, check the thread there to be up-to-date about what's happening here

**Closed by jvican** 2019-02-19 08:23 UTC
Labels: duplicate, task / compile
