### ISSUE TITLE
Overriding application.conf settings fails

### ISSUE THREAD

**Issue by kbreidenbach** [scalacenter/bloop#1144] opened 2020-01-13 21:43 UTC
I have a required application.conf setting ($KAFKA_BOOTSTRAP_SERVERS) in `main/resources/application.conf` which I override in `test/resources/application.conf`. When I run `sbt clean test` the build passes, but with bloop it fails to read the application.conf in the test resources folder and I get:

```
com.rewardsnetwork.decisionator.persistence.DataAccessSpec *** ABORTED ***
  pureconfig.error.ConfigReaderException: Cannot convert configuration to a com.rewardsnetwork.decisionator.config.DecisionatorConfig. Failures are:
  - (file:/Users/kbreidenbach/Development/scala/dff-decisionator/src/main/resources/application.conf:18) Unable to parse the configuration: Could not resolve substitution to a value: ${KAFKA_BOOTSTRAP_SERVERS}.
  at pureconfig.module.catseffect.package$.$anonfun$loadF$2(package.scala:23)
  at cats.syntax.EitherOps$.leftMap$extension(either.scala:151)
  at pureconfig.module.catseffect.package$.$anonfun$loadF$1(package.scala:23)
  at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:185)
  at cats.effect.IO.unsafeRunTimed(IO.scala:320)
  at cats.effect.IO.unsafeRunSync(IO.scala:239)
  at com.rewardsnetwork.decisionator.persistence.DataAccessSpec.<init>(DataAccessSpec.scala:34)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
```

This may be a reintroduction of the bug from this issue: https://github.com/scalacenter/bloop/issues/102

`bloop about`:
```
bloop v1.4.0-RC1

Using Scala v2.12.8 and Zinc v1.3.0-M4+32-b1accb96
Running on Java JDK v12.0.1 (/Library/Java/JavaVirtualMachines/adoptopenjdk-12.0.1.jdk/Contents/Home)
  -> Supports debugging user code, Java Debug Interface (JDI) is available.
Maintained by the Scala Center (Jorge Vicente Cantero, Martin Duhem)
```

**Comment by sloshy** [comment] 2020-01-13 21:54
@kbreidenbach and I found a temporary workaround for now: if you rename `test/resources/application.conf` to some other name, then it loads just fine. I think the root of the problem is a namespace conflict since it is trying to load the resource from the main resources folder first.

**Comment by jvican** [comment] 2020-01-14 01:37
Thanks for reporting. Bloop tries really hard to reproduce the same classpath as the source build tool, but sometimes it's not possible. Could you folks have a look at the classpath of the project you're running and see the order of the classpath entries? Could you compare that with `dependencyClasspath` of the same project in sbt?

`getResource` follows the classpath order to find the first matched resource. If we find why the order is different, we might be able to find a fix for this in sbt-bloop itself.

**Comment by jvican** [comment] 2020-01-26 00:23
ping @kbreidenbach

**Comment by jvican** [comment] 2020-01-30 00:57
Hey @kbreidenbach, need some of your input here. Otherwise I'll need to close since this ticket is not actionable as it is.

**Comment by kbreidenbach** [comment] 2020-01-30 19:11
Sorry for the delay. Please find attached a test project that you can use to see the issue.

If you run with sbt you will see:
```
sbt clean test                                                                                                                 12:44❖
[info] Loading global plugins from /Users/kbreidenbach/.sbt/1.0/plugins
[info] Loading settings for project bloop-error-build from plugins.sbt,metals.sbt ...
[info] Loading project definition from /Users/kbreidenbach/Development/scala/bloop-error/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to bloop-error (in build file:/Users/kbreidenbach/Development/scala/bloop-error/)
[success] Total time: 0 s, completed Jan 30, 2020 1:04:34 PM
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Compiling 2 Scala sources to /Users/kbreidenbach/Development/scala/bloop-error/target/scala-2.12/classes ...
[info] Compiling 1 Scala source to /Users/kbreidenbach/Development/scala/bloop-error/target/scala-2.12/test-classes ...
[info] TestConfigSpec:
[info] - should read the src/test/resources/application.conf file
[info] Run completed in 1 second, 925 milliseconds.
[info] Total number of tests run: 1
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[success] Total time: 11 s, completed Jan 30, 2020 1:04:45 PM
```

Running bloop install gives:
```
sbt bloopInstall                                                                                                               13:04❖
[info] Loading global plugins from /Users/kbreidenbach/.sbt/1.0/plugins
[info] Loading settings for project bloop-error-build from plugins.sbt,metals.sbt ...
[info] Loading project definition from /Users/kbreidenbach/Development/scala/bloop-error/project
[info] Loading settings for project root from build.sbt ...
[info] Set current project to bloop-error (in build file:/Users/kbreidenbach/Development/scala/bloop-error/)
[success] Generated .bloop/root.json
[success] Generated .bloop/root-it.json
[success] Generated .bloop/root-test.json
[success] Total time: 1 s, completed Jan 30, 2020 1:05:02 PM
```

Trying to test with bloop gives this error:
```
bloop test root --watch                                                                                                        13:05❖

Compiling root (2 Scala sources)
Compiled root (1547ms)
Compiling root-test (1 Scala source)
Compiled root-test (1060ms)
TestConfigSpec:
- should read the src/test/resources/application.conf file *** FAILED ***
  pureconfig.error.ConfigReaderException: Cannot convert configuration to a test.TestConfig. Failures are:
  - (file:/Users/kbreidenbach/Development/scala/bloop-error/src/main/resources/application.conf:2) Unable to parse the configuration: Could not resolve substitution to a value: ${MY_ENV}.
  at pureconfig.module.catseffect.package$.$anonfun$loadF$2(package.scala:23)
  at cats.syntax.EitherOps$.leftMap$extension(either.scala:151)
  at pureconfig.module.catseffect.package$.$anonfun$loadF$1(package.scala:23)
  at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:185)
  at cats.effect.IO.unsafeRunTimed(IO.scala:320)
  at cats.effect.IO.unsafeRunSync(IO.scala:239)
  at test.TestConfigSpec.$anonfun$new$1(TestConfigSpec.scala:14)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  ...
Execution took 0.45s
1 tests, 1 failed
```

Hopefully this will be more useful than the classpaths from our internal project.

[bloop-error.tar.gz](https://github.com/scalacenter/bloop/files/4135841/bloop-error.tar.gz)

**Comment by jvican** [comment] 2020-01-31 11:31
This is very useful. Thank you, will have a look.

**Closed** 2020-03-16 22:47 UTC
Labels: bug, integrations, sbt, task / run, task / test
