### ISSUE TITLE
Obtained setrlimit to increase file descriptor limit failed, errno 22

### ISSUE THREAD

**Issue by jeffrey-aguilera** [scalacenter/bloop#1326] opened 2020-06-24 06:18 UTC
Description is error reported when running bloop 1.4.2 on macos Catalina 10.15.5

**Comment by jvican** [comment] 2020-06-26 14:50
There are literally so many things that could be happening here... This ticket lacks version information and context and it's not actionable for the maintainers of the project. It's not even clear to me this is caused by Bloop itself. I'm closing, feel free to reopen if you can guarantee this is an error caused by bloop and can provide the context needed for people to look into this.

**Closed** 2020-06-26 14:50 UTC
