### ISSUE TITLE
Unexpected "discarded non-Unit value" warning from type inference

### ISSUE THREAD

**Issue by ctataryn** [scalacenter/bloop#1334] opened 2020-07-04 18:51 UTC
I have the following code:

```scala
  def subtitlesGetForDistributionRoute(distributionId: UUID, paramMap: Map[String, List[String]], settings: CsSettingsImpl) = {
    if (paramMap.exists(_ == ("srt", List("1")))) {
      subtitlesGetSRTForDistributionRoute(distributionId, paramMap.exists(_ == ("asFile", List("1"))))
    } else if (paramMap.exists(_ == ("vtt", List("1")))) {
      subtitlesGetVTTForDistributionRoute(distributionId, paramMap.exists(_ == ("asFile", List("1"))))
    } else if (paramMap.exists(_ == ("text", List("1")))) {
      subtitlesGetTextTranscriptForDistributionRoute(distributionId, paramMap.exists(_ == ("asFile", List("1"))))
    } else if (paramMap.exists(_ == ("wiki", List("1")))) {
      subtitlesGetWikiForDistributionRoute(distributionId, paramMap.exists(_ == ("asFile", List("1"))), settings)
    } else if (paramMap.exists(_ == ("html", List("1")))) {
      subtitlesGetHtmlForDistributionRoute(distributionId, paramMap.exists(_ == ("asFile", List("1"))), settings)
    } else {
      subtitlesGetDistributionRoute(distributionId)
    }
  }
```

In VSCode, bloop highlights each function call in in yellow within the `if` statement and claims:

`discarded non-Unit value`

I know the code is really ugly, but it is valid as far as I can tell. Whatever branch of if statement is reached, that will be the return value of the function.

![image](https://user-images.githubusercontent.com/435719/86519097-1e3e5b00-bdfd-11ea-8327-9ec868a40860.png)

**Comment by olafurpg** [comment] 2020-07-06 16:01
Thank you for reporting! These warning are reported by the Scala compiler by respecting the compiler options that are defined in your `build.sbt`, Bloop only forwards them. Can you elaborate on what is your expected behavior?

**Comment by ctataryn** [comment] 2020-07-07 13:32
@olafurpg I have the following scalac options in my build.sbt:

```
scalacOptions := Seq(
    "-feature",
    "-unchecked",
    "-deprecation",
    "-Ywarn-value-discard",
    "-encoding", "utf8")
```

When I run `;clean;compile` from sbt I don't get a warning like the one stated in this issue.

The expected behaviour would be to not issue a warning because the functions in each branch of the if-statement renders a value which is not actually discarded (it should be the return value of the if statement, and thus the return value of the function).  Unless I'm missing something?

**Comment by jvican** [comment] 2020-07-07 21:49
@ctataryn Thanks for reporting! Your issue might just be related to the incremental compiler. If you're not compiling the caller, which forces the return type to be non-unit, then the compiler might assume this returns a `Unit` and give you that warning. I don't see a way we can fix this in bloop itself, it's more of a compiler-specific thing.
  
Have you tried to run `bloop clean --propagate $YOUR_PROJECT` and compile it again? I would also encourage you to ascribe the return type of the method.

**Comment by jvican** [comment] 2020-07-09 12:50
Closing because I believe this is unrelated to bloop. Please feel free to reopen or comment when you can have a look at this

**Closed by jvican** 2020-07-09 12:50 UTC
Labels: community, docs, task / compile
