### ISSUE TITLE
--watch prints out a lot of noise and false compile errors

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bloop#257] opened 2018-02-12 11:09 UTC
At commit https://github.com/olafurpg/vork/commit/85e63f7dff59b2a6051f77fbea0c7ed3e17b4a80
```
$ bloop compile -p vork --watch
Compiling 19 Scala sources to /Users/ollie/dev/vork/vork/target/scala-2.12/classes ...
Done compiling. // All OK
// add single newline to Processor.scala
Compiling 2 Scala sources to /Users/ollie/dev/vork/runtime/target/scala-2.12/classes ...
Compiling 2 Scala sources to /Users/ollie/dev/vork/runtime/target/scala-2.12/classes ...
Compiling 2 Scala sources to /Users/ollie/dev/vork/runtime/target/scala-2.12/classes ...
Compiling 1 Scala source to /Users/ollie/dev/vork/vork/target/scala-2.12/classes ...
Compiling 2 Scala sources to /Users/ollie/dev/vork/runtime/target/scala-2.12/classes ...
Done compiling.
[W]  [E-1] there were three deprecation warnings (since 2.11.0); re-run with -deprecation for details
[W]  [E-1] there were three deprecation warnings (since 2.11.0); re-run with -deprecation for details
[W]  [E-1] there were three deprecation warnings (since 2.11.0); re-run with -deprecation for details
Done compiling.
Done compiling.
Done compiling.
[W]  [E-1] there were three deprecation warnings (since 2.11.0); re-run with -deprecation for details
Done compiling.
Compiling 2 Scala sources to /Users/ollie/dev/vork/runtime/target/scala-2.12/classes ...
Compiling 19 Scala sources to /Users/ollie/dev/vork/vork/target/scala-2.12/classes ...
Compiling 19 Scala sources to /Users/ollie/dev/vork/vork/target/scala-2.12/classes ...
Compiling 19 Scala sources to /Users/ollie/dev/vork/vork/target/scala-2.12/classes ...
Compiling 19 Scala sources to /Users/ollie/dev/vork/vork/target/scala-2.12/classes ...
[W]  [E-1] there were three deprecation warnings (since 2.11.0); re-run with -deprecation for details
Done compiling.
Compiling 19 Scala sources to /Users/ollie/dev/vork/vork/target/scala-2.12/classes ...
[E] [E14] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type Section
[E]       L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                   ^
[E] [E13] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       value empty is not a member of object org.langmeta.semanticdb.Document
[E]       L168:         Document.empty
[E]                              ^
[E] [E12] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type DocumentBuilder
[E]       L165:         cls.newInstance().asInstanceOf[DocumentBuilder].$doc.build()
[E]                                                    ^
[E] [E11] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type Section
[E]       L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                   ^
[E] [E10] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type Section
[E]       L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                   ^
[E] [E9] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      value mod is not a member of Any
[E]      L34:           case (a, b) => EvaluatedSection(a, b.source, b.mod)
[E]                                                                    ^
[E] [E8] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      value source is not a member of Any
[E]      L34:           case (a, b) => EvaluatedSection(a, b.source, b.mod)
[E]                                                          ^
[E] [E7] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      value sections is not a member of meta.Document
[E]      L33:         document.sections.zip(trees).map {
[E]                            ^
[E] [E6] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      not found: type Section
[E]      L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                  ^
[E] [E5] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L24: import vork.runtime.Macros
[E]                       ^
[E] [E4] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L23: import vork.runtime.DocumentBuilder
[E]                       ^
[E] [E3] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L22: import vork.runtime.Document
[E]                       ^
[E] [E2] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      not found: type Section
[E]      L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                  ^
[E] [E1] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L25: import vork.runtime.Section
[E]                       ^
[E] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala: L22 [E3], L23 [E4], L24 [E5], L25 [E1], L33 [E7], L34 [E8], L34 [E9], L38 [E2], L38 [E6], L38 [E10], L38 [E11], L38 [E14], L165 [E12], L168 [E13]
[E] Compilation failed because of the following reasons:
[E] [E14] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type Section
[E]       L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                   ^
[E] [E13] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       value empty is not a member of object org.langmeta.semanticdb.Document
[E]       L168:         Document.empty
[E]                              ^
[E] [E12] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type DocumentBuilder
[E]       L165:         cls.newInstance().asInstanceOf[DocumentBuilder].$doc.build()
[E]                                                    ^
[E] [E11] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type Section
[E]       L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                   ^
[E] [E10] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type Section
[E]       L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                   ^
[E] [E9] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      value mod is not a member of Any
[E]      L34:           case (a, b) => EvaluatedSection(a, b.source, b.mod)
[E]                                                                    ^
[E] [E8] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      value source is not a member of Any
[E]      L34:           case (a, b) => EvaluatedSection(a, b.source, b.mod)
[E]                                                          ^
[E] [E7] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      value sections is not a member of meta.Document
[E]      L33:         document.sections.zip(trees).map {
[E]                            ^
[E] [E6] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      not found: type Section
[E]      L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                  ^
[E] [E5] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L24: import vork.runtime.Macros
[E]                       ^
[E] [E4] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L23: import vork.runtime.DocumentBuilder
[E]                       ^
[E] [E3] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L22: import vork.runtime.Document
[E]                       ^
[E] [E2] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      not found: type Section
[E]      L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                  ^
[E] [E1] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L25: import vork.runtime.Section
[E]                       ^
[E] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala: L22 [E3], L23 [E4], L24 [E5], L25 [E1], L33 [E7], L34 [E8], L34 [E9], L38 [E2], L38 [E6], L38 [E10], L38 [E11], L38 [E14], L165 [E12], L168 [E13]
[E] Compilation failed because of the following reasons:
[E] [E14] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type Section
[E]       L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                   ^
[E] [E13] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       value empty is not a member of object org.langmeta.semanticdb.Document
[E]       L168:         Document.empty
[E]                              ^
[E] [E12] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type DocumentBuilder
[E]       L165:         cls.newInstance().asInstanceOf[DocumentBuilder].$doc.build()
[E]                                                    ^
[E] [E11] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type Section
[E]       L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                   ^
[E] [E10] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type Section
[E]       L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                   ^
[E] [E9] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      value mod is not a member of Any
[E]      L34:           case (a, b) => EvaluatedSection(a, b.source, b.mod)
[E]                                                                    ^
[E] [E8] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      value source is not a member of Any
[E]      L34:           case (a, b) => EvaluatedSection(a, b.source, b.mod)
[E]                                                          ^
[E] [E7] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      value sections is not a member of meta.Document
[E]      L33:         document.sections.zip(trees).map {
[E]                            ^
[E] [E6] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      not found: type Section
[E]      L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                  ^
[E] [E5] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L24: import vork.runtime.Macros
[E]                       ^
[E] [E4] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L23: import vork.runtime.DocumentBuilder
[E]                       ^
[E] [E3] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L22: import vork.runtime.Document
[E]                       ^
[E] [E2] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      not found: type Section
[E]      L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                  ^
[E] [E1] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L25: import vork.runtime.Section
[E]                       ^
[E] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala: L22 [E3], L23 [E4], L24 [E5], L25 [E1], L33 [E7], L34 [E8], L34 [E9], L38 [E2], L38 [E6], L38 [E10], L38 [E11], L38 [E14], L165 [E12], L168 [E13]
[E] Compilation failed because of the following reasons:
[E] [E14] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type Section
[E]       L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                   ^
[E] [E13] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       value empty is not a member of object org.langmeta.semanticdb.Document
[E]       L168:         Document.empty
[E]                              ^
[E] [E12] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type DocumentBuilder
[E]       L165:         cls.newInstance().asInstanceOf[DocumentBuilder].$doc.build()
[E]                                                    ^
[E] [E11] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type Section
[E]       L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                   ^
[E] [E10] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]       not found: type Section
[E]       L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                   ^
[E] [E9] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      value mod is not a member of Any
[E]      L34:           case (a, b) => EvaluatedSection(a, b.source, b.mod)
[E]                                                                    ^
[E] [E8] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      value source is not a member of Any
[E]      L34:           case (a, b) => EvaluatedSection(a, b.source, b.mod)
[E]                                                          ^
[E] [E7] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      value sections is not a member of meta.Document
[E]      L33:         document.sections.zip(trees).map {
[E]                            ^
[E] [E6] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      not found: type Section
[E]      L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                  ^
[E] [E5] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L24: import vork.runtime.Macros
[E]                       ^
[E] [E4] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L23: import vork.runtime.DocumentBuilder
[E]                       ^
[E] [E3] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L22: import vork.runtime.Document
[E]                       ^
[E] [E2] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      not found: type Section
[E]      L38:   case class EvaluatedSection(section: Section, source: Source, mod: FencedCodeMod) {
[E]                                                  ^
[E] [E1] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala
[E]      object runtime is not a member of package vork
[E]      L25: import vork.runtime.Section
[E]                       ^
[E] /src/main/scala/vork/markdown/processors/MarkdownCompiler.scala: L22 [E3], L23 [E4], L24 [E5], L25 [E1], L33 [E7], L34 [E8], L34 [E9], L38 [E2], L38 [E6], L38 [E10], L38 [E11], L38 [E14], L165 [E12], L168 [E13]
[E] Compilation failed because of the following reasons:
[E] Error: Could not find or load main class vork.Cli
```

I have no idea why the compile errors happen when I add a single newline to my file. I cannot reproduce without --watch.

**Comment by jvican** [comment] 2018-03-12 16:43
@olafurpg I cannot reproduce this issue anymore, I think it's fixed in master. Can you try this out when M6 is out? We're cutting the release now.

**Comment by Duhemm** [comment] 2018-03-12 21:55
I can't even reproduce in M5 actually...

**Comment by Duhemm** [comment] 2018-03-12 22:04
@jvican Can you try inside IntelliJ? I can't reproduce with M4 + Vim

**Comment by jvican** [comment] 2018-03-12 22:24
OK, was able to reproduce this issue within Intellij. It seems to do a weird thing. Investigating yet.

**Closed** 2018-03-14 15:51 UTC
Labels: bug, task / compile, task / watch
