### ISSUE TITLE
Run does not register file watcher

### ISSUE THREAD

**Issue by tindzk** [scalacenter/bloop#475] opened 2018-05-06 19:00 UTC
When I run `compile` with the `--watch` parameter, the output is:

```shell
$ bloop compile --watch project
Watching 2 directories... (press C-c to interrupt)
```

However, `bloop run --watch project` does not set up any file watchers.

**Comment by jvican** [comment] 2018-05-06 20:53
Strange, `test -w` works. Does `bloop run --watch project` at least run the application once? Because if it doesn't, then the problem is that the main class is not found or you're not running the application in the right project.

**Comment by tindzk** [comment] 2018-05-07 07:51
Yes, the command runs the application, but does not restart it when changes to the sources were made.

**Comment by jarrodu** [comment] 2018-05-18 09:55
When I edit my file and save the bloop server does not pick up on the changes.

I am running on Ubuntu and using the developer version of bloop. I had the same problem with 1.0.0-M10.
```
➜  ~ bloop server
Unable to load nailgun-version.properties.
NGServer [UNKNOWN] started on address localhost/127.0.0.1 port 8212.
```

```
    Bloop-frontend version    `1.0.0-M10+21-76187ec5`
    Zinc version     `1.1.7+62-0f4ad9d5`
    Scala version    `2.12.4`
```

```
➜  bloop-watch-example git:(master) ✗ bloop run --watch --verbose bloop-watch-example
[D] Loading 2 projects from '/home/jarrodu/Projects/personal-projects/bloop-watch-example/.bloop'...
[D] Loading project from '/home/jarrodu/Projects/personal-projects/bloop-watch-example/.bloop/bloop-watch-example.json'
[D] Loading project from '/home/jarrodu/Projects/personal-projects/bloop-watch-example/.bloop/bloop-watch-example-test.json'
[D] Cache miss for scala instance org.scala-lang:scala-compiler:2.12.6.
[D]   => /home/jarrodu/.sbt/boot/scala-2.12.6/lib/jline.jar
[D]   => /home/jarrodu/.sbt/boot/scala-2.12.6/lib/scala-compiler.jar
[D]   => /home/jarrodu/.sbt/boot/scala-2.12.6/lib/scala-library.jar
[D]   => /home/jarrodu/.sbt/boot/scala-2.12.6/lib/scala-reflect.jar
[D]   => /home/jarrodu/.sbt/boot/scala-2.12.6/lib/scala-xml_2.12.jar
[D] Missing analysis file for project 'bloop-watch-example-test'
[D] Loading previous analysis for 'bloop-watch-example' from '/home/jarrodu/Projects/personal-projects/bloop-watch-example/.bloop/bloop-watch-example/bloop-watch-example-analysis.bin'.
[D] Scheduled compilation of 'bloop-watch-example' starting at 11:50:45.662.
[D] 
[D] Initial source changes: 
[D] 	removed:Set()
[D] 	added: Set()
[D] 	modified: Set(/home/jarrodu/Projects/personal-projects/bloop-watch-example/main.scala)
[D] Invalidated products: Set(/home/jarrodu/Projects/personal-projects/bloop-watch-example/.bloop/bloop-watch-example/scala-2.12/classes/Hello$.class, /home/jarrodu/Projects/personal-projects/bloop-watch-example/.bloop/bloop-watch-example/scala-2.12/classes/Hello$delayedInit$body.class, /home/jarrodu/Projects/personal-projects/bloop-watch-example/.bloop/bloop-watch-example/scala-2.12/classes/Hello.class)
[D] External API changes: API Changes: Set()
[D] Modified binary dependencies: Set()
[D] Initial directly invalidated classes: Set(Hello)
[D] 
[D] Sources indirectly invalidated by:
[D] 	product: Set(/home/jarrodu/Projects/personal-projects/bloop-watch-example/main.scala)
[D] 	binary dep: Set()
[D] 	external source: Set()
[D] All sources are invalidated.
[D] Recompiling all 1 sources: invalidated sources (1) exceeded 50.0% of all sources
Compiling 1 Scala source to /home/jarrodu/Projects/personal-projects/bloop-watch-example/.bloop/bloop-watch-example/scala-2.12/classes ...
[D] Returning already retrieved and compiled bridge: /home/jarrodu/.cache/bloop/components/ch.epfl.scala-compiler-bridge_2.12-1.1.7+62-0f4ad9d5-bin_2.12.6__52.0/ch.epfl.scala-compiler-bridge_2.12-1.1.7+62-0f4ad9d5-bin_2.12.6__52.0.jar.
[D] Returning already retrieved and compiled bridge: /home/jarrodu/.cache/bloop/components/ch.epfl.scala-compiler-bridge_2.12-1.1.7+62-0f4ad9d5-bin_2.12.6__52.0/ch.epfl.scala-compiler-bridge_2.12-1.1.7+62-0f4ad9d5-bin_2.12.6__52.0.jar.
[D] [zinc] Running cached compiler c188793 for Scala compiler version 2.12.6
[D] [zinc] The Scala compiler is invoked with:
[D] 	-bootclasspath
[D] 	/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes:/home/jarrodu/.sbt/boot/scala-2.12.6/lib/scala-library.jar
[D] 	-classpath
[D] 	/home/jarrodu/Projects/personal-projects/bloop-watch-example/.bloop/bloop-watch-example/scala-2.12/classes
[D] Scala compilation took 3.618191068 s
Done compiling.
[D] digraph "generated-graph" {
[D]  graph [ranksep=0, rankdir=LR];
[D]   "bloop-watch-example (success 4268ms)" [label="bloop-watch-example (success 4268ms)"];
[D]   
[D]   bloop-watch-example (success 4268ms)
[D] }
[D] Found 1 main classes: Hello.
[D] Running 'Hello' in a new JVM.
[D] 
[D] Fork options:
[D]    command      = '/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -cp /home/jarrodu/Projects/personal-projects/bloop-watch-example/.bloop/bloop-watch-example/scala-2.12/classes:/home/jarrodu/.sbt/boot/scala-2.12.6/lib/scala-library.jar Hello'
[D]    cwd          = '/home/jarrodu/Projects/personal-projects/bloop-watch-example'
[D]    classpath    = '/home/jarrodu/Projects/personal-projects/bloop-watch-example/.bloop/bloop-watch-example/scala-2.12/classes:/home/jarrodu/.sbt/boot/scala-2.12.6/lib/scala-library.jar'
[D]    java_home    = '/usr/lib/jvm/java-8-openjdk-amd64/jre'
[D]    java_options = '
Hello Cats and Bats
[D] The process is closed; emptying out buffer.
[D] Forked JVM exited with code 0
[D] Forked JVM exited with code: 0
Watching 0 directories and 1 files... (press C-c to interrupt)
[D] /home/jarrodu/Projects/personal-projects/bloop-watch-example/main.scala
[D] Assuming ExtendedWatchEventModifier.FILE_TREE is not supported
```

**Comment by jarrodu** [comment] 2018-06-19 09:01
I think this might be fixed with M11.
I can't reproduce the bug any more. :+1:

**Closed** 2018-06-21 18:36 UTC
Labels: bug, good first issue, help wanted, task / run
