### ISSUE TITLE
Experienced slowdown when starting sbt with sbt-bloop

### ISSUE THREAD

**Issue by JD557** [scalacenter/bloop#1228] opened 2020-04-01 11:29 UTC
Using
* SBT 1.3.8
* Scala 2.12.10,
* SBT-Bloop: 1.4.0-RC1

I get the following times:

## Without sbt-bloop (second run)

```
$ time sbt version
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=1G; support was removed in 8.0
[info] Loading settings for project global-plugins from idea.sbt,plugins.sbt ...
[info] Loading global plugins from /Users/joao/.sbt/1.0/plugins
[info] Loading settings for project [REDACTED] from credentials.sbt,plugins.sbt,metals.sbt ...
[info] Loading project definition from [REDACTED]
[info] Loading settings for project [REDACTED] from build.sbt ...
[info] Resolving key references (99462 settings) ...
[REDACTED]
sbt version  77.23s user 3.75s system 361% cpu 22.396 total
```

## With sbt-bloop (second run)

```
$ time sbt version
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=1G; support was removed in 8.0
[info] Loading settings for project global-plugins from idea.sbt,plugins.sbt ...
[info] Loading global plugins from /Users/joao/.sbt/1.0/plugins
[info] Loading settings for project [REDACTED] from credentials.sbt,plugins.sbt,metals.sbt ...
[info] Loading project definition from [REDACTED]
[info] Loading settings for project [REDACTED] from build.sbt ...
[info] Resolving key references (104723 settings) ...
[REDACTED]
sbt version  111.85s user 17.71s system 154% cpu 1:24.00 total
```

The project in question has ~70 subprojects. Running `ls -l | wc -l` inside `.bloop` after `sbt bloopInstall` returns 231 files, while `ls -lR | wc -l` returns 1447 files.

Running sbt with `-Dsbt.task.timings=true` doesn't show anything in particular (most of the time is spent after the "Resolving key references" and doesn't show on the output).

**Comment by jvican** [comment] 2020-04-02 11:29
Thanks for reporting @JD557. If most of the time is spent after "Resolving key references", it looks like something might be running here as an `onLoad` hook. We need to know what. Can you run `sbt  -debug` and tell me what's running?

**Comment by JD557** [comment] 2020-04-02 12:19
Running `sbt -debug`, I get:

```
[debug] "not up to date. inChanged = true, force = false
[debug] Updating ProjectRef(uri("file:/Users/joao/.sbt/1.0/plugins/"), "global-plugins")...
[debug] Done updating ProjectRef(uri("file:/Users/joao/.sbt/1.0/plugins/"), "global-plugins")
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[debug] Full compilation, no sources in previous analysis.
[debug] Copy resource mappings:
[debug]
[debug] Other repositories:
[debug] Default repositories:
[debug] Using inline dependencies specified in Scala.
[debug] "not up to date. inChanged = true, force = false
[debug] Updating ProjectRef([REDACTED])...
[debug] Done updating ProjectRef([REDACTED])
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[debug] No changes
[debug] Copy resource mappings:
[debug]
[debug] Checking for meta build source updates
[debug] Checking for meta build source updates
[debug] Checking for meta build source updates
[debug] Checking for meta build source updates
[debug] Checking for meta build source updates
```

Where most of the time is spent on the second `[debug] Copy resource mappings:`

I was expecting more logs from a `-debug` flag, am I missing some argument?

**Comment by jvican** [comment] 2020-04-02 13:07
I guess that's about it. If nothing is bloop-related running with the debug log level enabled, then this is likely not caused by bloop at all and it's just sbt being slow to load our plugin. `sbt-bloop` doesn't do anything out of the ordinary at boot time by default. I would double-check your numbers and make sure you're not profiling something else.

**Comment by jvican** [comment] 2020-04-06 09:05
@JD557 If you find some more evidence that sbt-bloop might be at fault here, let me know and I'll reopen the ticket. Let's close for now

**Closed by jvican** 2020-04-06 09:05 UTC
Labels: integrations, performance, sbt
